
project_id = "btcwmuyemmkiteqlopce"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54323

[studio]
port = 54323

[functions.calendly-webhook]
verify_jwt = false

[functions.lead-generation-webhook]
verify_jwt = false

[functions.check-assignability]
verify_jwt = false
